17 01 23
dimonaks/siman pull request #33
Opened 2023-01-16 21:35 UTC by antonboev22

2023-01-19 14:28 UTC, dimonaks commented on siman/analysis.py
> +    import numpy as np
Добавить описание функции

2023-01-19 14:31 UTC, dimonaks commented on siman/calc_manage.py
> +                print(type(input_st), Structure, isinstance(input_st, Structure))
Либо убрать print либо уточнить, чтобы понятно было что выводится

2023-02-03 10:38 UTC, dimonaks commented on siman/matproj_functions.py
> +def calc_bulk_list2(data_list, suf = '', ise = '8m', status = None, up =None, corenum = 1, add_loop_dic={},path=None):
Описание в соответствии с форматом. Нужно более понятное название и описание. Можно обсудить.

2023-02-03 10:38 UTC, dimonaks requested changes
смотри комменты по коду

2023-02-07 11:49 UTC, antonboev22 commented on siman/analysis.py
> +    import numpy as np
Добавил

2023-02-07 11:49 UTC, antonboev22 commented on siman/calculators/vasp.py
> +import numpy as np
здесь не хватало импорта numpy

2023-02-07 11:49 UTC, antonboev22 commented on siman/core/calculation.py
> -                ax = axs[i]
здесь была ошибка если один атом указываешь

2023-02-07 11:49 UTC, antonboev22 commented on siman/dos_functions.py
> +            # numbers_list.append([iatom2]) # for cl2 only one atom is supported
здесь дос не работал для двух структур

2023-02-07 11:49 UTC, antonboev22 commented on siman/matproj_functions.py
> +def calc_bulk_list2(data_list, suf = '', ise = '8m', status = None, up =None, corenum = 1, add_loop_dic={},path=None):
этот модуль я позже переделаю полностью

2023-02-08 08:19 UTC, dimonaks approved these changes
Принял, на будущее:
1. Описание функций нужно по этому формату делать https://github.com/dimonaks/siman/wiki/Develop
2. Сделать тест всех режимов plot_dos

2023-02-08 08:20 UTC, merged